# Generated by Django 6.0 on 2025-12-04 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(help_text='Ordem em que a etapa aparece no fluxo.')),
                ('mostrar_no_dashboard', models.BooleanField(default=True, help_text='Define se essa etapa aparecerá nos cards do dashboard.')),
                ('is_checkin', models.BooleanField(default=False, help_text='Marque apenas na etapa que representa o CHECK-IN.')),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='core.oficina')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ('ordem',),
            },
        ),
        migrations.CreateModel(
            name='ConfigFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: Frente do veículo, Traseira, Painel KM', max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_fotos', to='core.oficina')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_fotos', to='core.etapa')),
            ],
            options={
                'verbose_name': 'Configuração de foto',
                'verbose_name_plural': 'Configurações de fotos',
                'ordering': ('ordem',),
            },
        ),
    ]
