# Generated by Django 6.0 on 2025-12-04 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_etapa_configfoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Número ou código da OS na oficina (ex.: número do sistema de orçamento).', max_length=50)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('modelo_veiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('cor_veiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(blank=True, null=True)),
                ('data_prevista_entrega', models.DateTimeField(blank=True, null=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('aberta', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etapa_atual', models.ForeignKey(blank=True, help_text='Etapa atual do processo desta OS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_na_etapa', to='core.etapa')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='core.oficina')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ('-criado_em',),
                'unique_together': {('oficina', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='FotoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PADRAO', 'Foto padrão'), ('LIVRE', 'Foto livre')], max_length=10)),
                ('arquivo', models.FileField(help_text='Caminho/arquivo da foto. No futuro pode ser apenas um link externo.', max_length=255, upload_to='os_fotos/')),
                ('titulo', models.CharField(blank=True, help_text="Opcional. Útil para fotos LIVRES (ex.: 'Detalhe amassado porta esquerda').", max_length=100, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('tirada_em', models.DateTimeField(auto_now_add=True)),
                ('config_foto', models.ForeignKey(blank=True, help_text='Preencher apenas se for foto padrão de CHECK-IN.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='core.configfoto')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.etapa')),
                ('tirada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_tiradas', to='core.usuariooficina')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.os')),
            ],
            options={
                'verbose_name': 'Foto da OS',
                'verbose_name_plural': 'Fotos da OS',
                'ordering': ('tirada_em',),
            },
        ),
    ]
