# Generated by Django 6.0 on 2025-12-09 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_os_fotoos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoos',
            name='drive_file_id',
            field=models.CharField(blank=True, help_text='ID do arquivo no Google Drive (se já enviado).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='os',
            name='drive_folder_id',
            field=models.CharField(blank=True, help_text='ID da pasta desta OS no Google Drive.', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OficinaDriveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_folder_id', models.CharField(help_text='ID da pasta raiz no Google Drive onde as OS desta oficina serão criadas.', max_length=255)),
                ('credentials_json', models.TextField(help_text='Credenciais OAuth serializadas (JSON) para acessar o Drive desta oficina.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oficina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_config', to='core.oficina')),
            ],
            options={
                'verbose_name': 'Configuração Google Drive',
                'verbose_name_plural': 'Configurações Google Drive',
            },
        ),
    ]
