# Generated by Django 6.0 on 2025-12-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fotoos_drive_file_id_os_drive_folder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoos',
            name='drive_file_id',
            field=models.CharField(blank=True, help_text='ID do arquivo correspondente no Google Drive.', max_length=255, null=True),
        ),
    ]
