# Generated by Django 5.2.6 on 2025-12-17 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_fotoos_drive_file_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservacaoEtapaOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observacoes_criadas",
                        to="core.usuariooficina",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes_os",
                        to="core.etapa",
                    ),
                ),
                (
                    "os",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes_etapas",
                        to="core.os",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observação da Etapa",
                "verbose_name_plural": "Observações das Etapas",
                "unique_together": {("os", "etapa")},
            },
        ),
    ]
