# Generated by Django 5.2.6 on 2025-12-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_observacaoetapaos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoos",
            name="etapa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fotos",
                to="core.etapa",
            ),
        ),
    ]
