# Generated by Django 5.2.6 on 2025-12-17 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_fotoos_etapa"),
    ]

    operations = [
        migrations.CreateModel(
            name="OSEtapaStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concluida_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_os",
                        to="core.etapa",
                    ),
                ),
                (
                    "os",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_etapas",
                        to="core.os",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status da etapa da OS",
                "verbose_name_plural": "Status das etapas da OS",
                "ordering": ("etapa__ordem", "id"),
                "unique_together": {("os", "etapa")},
            },
        ),
    ]
