# Generated by Django 6.0 on 2025-12-04 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_is_atual_usuariooficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo_resposta', models.CharField(choices=[('TEXTO', 'Texto'), ('ESCOLHA', 'Escolha')], max_length=10)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_perguntas', to='core.etapa')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_perguntas', to='core.oficina')),
            ],
            options={
                'verbose_name': 'Pergunta de check-in',
                'verbose_name_plural': 'Perguntas de check-in',
                'ordering': ('oficina', 'etapa', 'ordem'),
            },
        ),
        migrations.CreateModel(
            name='CheckinPerguntaOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='core.checkinpergunta')),
            ],
            options={
                'verbose_name': 'Opção de pergunta de check-in',
                'verbose_name_plural': 'Opções de perguntas de check-in',
                'ordering': ('pergunta', 'ordem'),
            },
        ),
    ]
