# Generated by Django 6.0 on 2025-12-04 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_checkin_perguntas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkinpergunta",
            name="etapa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkin_perguntas",
                to="core.etapa",
            ),
        ),
    ]
